#Specify version 
version: '3'

#For creating a multi-service architecture
services:
  web: #Service name 
    build: . #Executes docker file in current directory 
    container_name: 'opl_backend' 
    volumes: #Mount 
      - ./src:/opl_backend
    ports: #Expose ports hostport:container port 
      - "9090:8000"
    command: sh -c "python3 manage.py runserver"
    environment: #Environment variables to be injected into os.environ 
      - DB_HOST=localhost 
      - DB_NAME=OPL
      - DB_USER=angelo 
      - DB_PASS=angelo 
    depends_on: #Dependency 
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=angelo 
      - POSTGRES_DB=OPL 
      - POSTGRES_PASSWORD=Brause134!
    volumes:
      - /home/admin/OPL_backup_files/opl-backup/docker-entrypoint-initdb.d/opl-backup