version: '3'

services:
  web:
    build: . #Build from current directory 
    command: python3 manage.py runserver 127.0.0.1:8080:8080
    volumes: #Map current directory to backend directory 
      - .:/backend
    ports:
      - "127.0.0.1:8000:8000"
    dns: 
      - 212.227.123.16
      - 8.8.8.8
    networks:
      - deployment
  db:
    image: postgres
    restart: always 
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: opl-dev
    volumes: 
      - ../sql/opl-backup.sql:/docker-entrypoint-initdb.d/opl-backup.sql 
    networks:
      - deployment

networks:
  deployment:
    driver: bridge

  

    
